server:
  port: 8080
  servlet:
    context-path: /constructor

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-sql: false
    open-in-view: false

security:
  token:
    issuer: "constructor"
    publicKey: "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDhNA5l01hI28xxdL/q2lVCB84wB4k20sK08WC1gMiBJ5EVX/wnjLoU8ydaPWY9U3o4T9/bI3yEmkWth5XdArKE6On0WBWr/j9swgoSXWSwpHK2pbp2AgMxif+aSvhs7o3+S168lD4fuwxFpd9KVLtUNT8EAhhaZ9n09HGtpKMy1QIDAQAB"
    privateKey: "MIICeAIBADANBgkqhkiG9w0BAQEFAASCAmIwggJeAgEAAoGBAOE0DmXTWEjbzHF0v+raVUIHzjAHiTbSwrTxYLWAyIEnkRVf/CeMuhTzJ1o9Zj1TejhP39sjfISaRa2Hld0CsoTo6fRYFav+P2zCChJdZLCkcralunYCAzGJ/5pK+Gzujf5LXryUPh+7DEWl30pUu1Q1PwQCGFpn2fT0ca2kozLVAgMBAAECgYA5Ug+sGUwqV0/FPQswUtxKj0QK85AYVTLb7WhJKntebFzATQsYYfhnJrDIhkJEr7+3H5WB6JlkAwRjM9SQSYR4V62bzbOvZHcnN8gcj5Pe00ueBuSSTZDlbJE7vCAWBgCYUfugV6qoHODpLK6Q//G13h8cNjXKV6DvXhxIG3nkYQJBAPbHawir738N+fdCOAUIWo3zDNG+QzM0OBDBJ+n89ONzV5Hel9HZaIFJkiHNqLes4BTXX4myJdLajCFgJbBFsO0CQQDpnkFAkK9ffl8WezyF/tZeh5+ZaZ4/qnMDXtLriTWutPVaTh+VPj6jOTFtY+kPdLpDmGzBqjLXZigHk0UD+RSJAkEA7F0WzIh57NTDLat0IoXczgcUqTQ2Ay4p4QpQo5IQMGaCYom0Gl/E88g2uj/UMJDZU7zxmd5S0gFXpIQFtS8bBQJBAIbnuTykkHEvk49y6Ndj+rypytMXd6fCMRpwJpKXMGXL36cfWAOh5x/whgdqW4puWKVyHtOTCjrypgkB1SffLSkCQQC3b+rSVFVUWra4VouD0XMb007ohAtVjvyBpUqVzfLjmWSVzPKe3r6Pz67tn8oYBjyCYnD/5eWYOfgEyDSKK29p"
    maxAgeSeconds: 86400000

